#
# Makefile for the linux kernel.
#

obj-$(CONFIG_MMC_RTKEMMC_PLUS)  := rtk_emmc.o
rtk_emmc-objs := rtkemmc.o rtksd_ops.o rtk_mmc_ioctl.o rtk_mmc_pinmux.o

obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc_raw.o




