#ifndef __RTK_MODULE_EVENT_HDMI_H__
#define __RTK_MODULE_EVENT_HDMI_H__
/*
######################################################################################
# HDMI EVENT DEFINE
######################################################################################
*/
typedef enum
{
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_INIT_EVENT_ID,
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_UNINIT_EVENT_ID,
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_OPEN_EVENT_ID,
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_CLOSE_EVENT_ID,
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_CONNECT_EVENT_ID,
    KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_DISCONNECT_EVENT_ID,
    KERNEL_HDMI_EVENT_EVENT_MAX
}KERNEL_HDMI_EVENT_EVENT_ID;

/*
######################################################################################
# HDMI EVENT TYPE DEFINE
######################################################################################
*/
typedef enum
{
    KERNEL_HDMI_EVENT_TYPE_ID,
    KERNEL_HDMI_TYPE_MAX
}KERNEL_HDMI_TYPE_ID;

/*
######################################################################################
# HDMI EVENT MERGER DW1 DEFINE
######################################################################################
*/
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_DISCONNECT    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_DISCONNECT_EVENT_ID)
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_CONNECT    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_CONNECT_EVENT_ID)
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_CLOSE    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_CLOSE_EVENT_ID)
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_OPEN    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_OPEN_EVENT_ID)
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_UNINIT    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_UNINIT_EVENT_ID)
#define   HDMI_DW1_EVENT_CALL_VFE_HDMI_DRV_INIT    MERGER_EVENT_DW1(EVENT_FW_KERNEL, KERNEL_HDMI_MODULE_ID, KERNEL_HDMI_EVENT_type_ID, KERNEL_HDMI_EVENT_CALL_VFE_HDMI_DRV_INIT_EVENT_ID)

#define rtd_hdmi_event_log(type, event, event_val, module_reserved)     rtd_kernel_event_log(type, KERNEL_HDMI_MODULE_ID, event, event_val, module_reserved)
#endif /* __RTK_MODULE_EVENT_HDMI_H__ */

