#ifndef __RTK_MODULE_EVENT_VBY1_STRING_H__
#define __RTK_MODULE_EVENT_VBY1_STRING_H__
/*
######################################################################################
# VBY1 EVENT STRING DEFINE
######################################################################################
*/
static struct event_event_s quickshow_vby1_fun_event[]={
    {QUICKSHOW_VBY1_FUN_SCALER_END_EVENT_ID, "SCALER_END"},
    {QUICKSHOW_VBY1_FUN_SCALER_START_EVENT_ID, "SCALER_START"},
    {QUICKSHOW_VBY1_FUN_HDMI_PORT_SCAN_END_EVENT_ID, "HDMI_PORT_SCAN_END"},
    {QUICKSHOW_VBY1_FUN_HDMI_PORT_SCAN_START_EVENT_ID, "HDMI_PORT_SCAN_START"},
    {QUICKSHOW_VBY1_FUN_PANEL_LAST_HANDLER_END_EVENT_ID, "PANEL_LAST_HANDLER_END"},
    {QUICKSHOW_VBY1_FUN_PANEL_LAST_HANDLER_START_EVENT_ID, "PANEL_LAST_HANDLER_START"},
    {QUICKSHOW_VBY1_FUN_PANEL_SEQ_2_END_EVENT_ID, "PANEL_SEQ_2_END"},
    {QUICKSHOW_VBY1_FUN_PANEL_SEQ_2_START_EVENT_ID, "PANEL_SEQ_2_START"},
    {QUICKSHOW_VBY1_FUN_PANEL_SEQ_1_END_EVENT_ID, "PANEL_SEQ_1_END"},
    {QUICKSHOW_VBY1_FUN_PANEL_SEQ_1_START_EVENT_ID, "PANEL_SEQ_1_START"},
    {QUICKSHOW_VBY1_FUN_SOURCE_SELECT_END_EVENT_ID, "SOURCE_SELECT_END"},
    {QUICKSHOW_VBY1_FUN_SOURCE_SELECT_START_EVENT_ID, "SOURCE_SELECT_START"},
    {QUICKSHOW_VBY1_FUN_I2C_END_EVENT_ID, "I2C_END"},
    {QUICKSHOW_VBY1_FUN_I2C_START_EVENT_ID, "I2C_START"},
    {QUICKSHOW_VBY1_FUN_PWM_END_EVENT_ID, "PWM_END"},
    {QUICKSHOW_VBY1_FUN_PWM_START_EVENT_ID, "PWM_START"},
    {QUICKSHOW_VBY1_FUN_GPIO_END_EVENT_ID, "GPIO_END"},
    {QUICKSHOW_VBY1_FUN_GPIO_START_EVENT_ID, "GPIO_START"},
    {QUICKSHOW_VBY1_FUN_SETUP_END_EVENT_ID, "SETUP_END"},
    {QUICKSHOW_VBY1_FUN_SETUP_START_EVENT_ID, "SETUP_START"},
    {QUICKSHOW_VBY1_FUN_VIPTABLEINIT_END_EVENT_ID, "VIPTABLEINIT_END"},
    {QUICKSHOW_VBY1_FUN_VIPTABLEINIT_START_EVENT_ID, "VIPTABLEINIT_START"},
    {QUICKSHOW_VBY1_FUN_SCALER_INITRPCSHAREMEM_END_EVENT_ID, "SCALER_INITRPCSHAREMEM_END"},
    {QUICKSHOW_VBY1_FUN_SCALER_INITRPCSHAREMEM_START_EVENT_ID, "SCALER_INITRPCSHAREMEM_START"},
    {QUICKSHOW_VBY1_FUN_FWIF_COLOR_SET_STRUCTCOLORDATAFACMODETYPE_QUICK_SHOW_END_EVENT_ID, "FWIF_COLOR_SET_STRUCTCOLORDATAFACMODETYPE_QUICK_SHOW_END"},
    {QUICKSHOW_VBY1_FUN_FWIF_COLOR_SET_STRUCTCOLORDATAFACMODETYPE_QUICK_SHOW_START_EVENT_ID, "FWIF_COLOR_SET_STRUCTCOLORDATAFACMODETYPE_QUICK_SHOW_START"},
    {QUICKSHOW_VBY1_FUN_NEWBASE_HDMI_RX_DETECT_TASK_END_EVENT_ID, "NEWBASE_HDMI_RX_DETECT_TASK_END"},
    {QUICKSHOW_VBY1_FUN_NEWBASE_HDMI_RX_DETECT_TASK_START_EVENT_ID, "NEWBASE_HDMI_RX_DETECT_TASK_START"},
    {QUICKSHOW_VBY1_FUN_HDMI_RX_INIT_END_EVENT_ID, "HDMI_RX_INIT_END"},
    {QUICKSHOW_VBY1_FUN_HDMI_RX_INIT_START_EVENT_ID, "HDMI_RX_INIT_START"},
    {QUICKSHOW_VBY1_FUN_VBY1_TX_END_EVENT_ID, "VBY1_TX_END"},
    {QUICKSHOW_VBY1_FUN_VBY1_TX_START_EVENT_ID, "VBY1_TX_START"},
    {QUICKSHOW_VBY1_FUN_UNMUTE_AUDIO_END_EVENT_ID, "UNMUTE_AUDIO_END"},
    {QUICKSHOW_VBY1_FUN_UNMUTE_AUDIO_START_EVENT_ID, "UNMUTE_AUDIO_START"},
    {QUICKSHOW_VBY1_FUN_RTK_AMP_INIT_END_EVENT_ID, "RTK_AMP_INIT_END"},
    {QUICKSHOW_VBY1_FUN_RTK_AMP_INIT_START_EVENT_ID, "RTK_AMP_INIT_START"},
    {QUICKSHOW_VBY1_FUN_RTK_AMP_INIT_START_EVENT_ID, "RTK_AMP_INIT_START"},
    {QUICKSHOW_VBY1_FUN_RTK_AMP_INIT_START_EVENT_ID, "RTK_AMP_INIT_START"},
    {EVENT_LIMIT_MAX,NULL},
};

/*
######################################################################################
# VBY1 EVENT TYPE STRING DEFINE
######################################################################################
*/
struct event_eventtype_s quickshow_vby1_eventtype[]={
    {QUICKSHOW_VBY1_FUN_TYPE_ID, "FUN", quickshow_vby1_fun_event},
    {EVENT_LIMIT_MAX,NULL,NULL},
};
#endif /* __RTK_MODULE_EVENT_VBY1_STRING_H__ */

