KASAN_LIST := \
 drivers/rtk_kdriver/atsc3_dmx  \
 drivers/rtk_kdriver/audio  \
 drivers/rtk_kdriver/audio/alsa  \
 drivers/rtk_kdriver/audio_hw/rtd6748  \
 drivers/rtk_kdriver/crt/rtd6748  \
 drivers/rtk_kdriver/cw  \
 drivers/rtk_kdriver/cw/scpu  \
 drivers/rtk_kdriver/ddc  \
 drivers/rtk_kdriver/delivery  \
 drivers/rtk_kdriver/demod/rtd6748  \
 drivers/rtk_kdriver/demod/rtd6748/demodcomm  \
 drivers/rtk_kdriver/demod/rtd6748/demodcore  \
 drivers/rtk_kdriver/dolby_idk_1_6_1_1  \
 drivers/rtk_kdriver/gal/rtd6748  \
 drivers/rtk_kdriver/gpio  \
 drivers/rtk_kdriver/hw_monitor  \
 drivers/rtk_kdriver/i2c/algos  \
 drivers/rtk_kdriver/i2c/busses  \
 drivers/rtk_kdriver/irtx/adapter  \
 drivers/rtk_kdriver/irtx/core  \
 drivers/rtk_kdriver/japan4k_dmx  \
 drivers/rtk_kdriver/mcp  \
 drivers/rtk_kdriver/mcp/napi  \
 drivers/rtk_kdriver/mcp/rcp  \
 drivers/rtk_kdriver/md  \
 drivers/rtk_kdriver/memc_isr/rtd6748  \
 drivers/rtk_kdriver/memc_isr/rtd6748/Common  \
 drivers/rtk_kdriver/memc_isr/rtd6748/Driver  \
 drivers/rtk_kdriver/memc_isr/rtd6748/HAL  \
 drivers/rtk_kdriver/memc_isr/rtd6748/MID  \
 drivers/rtk_kdriver/memc_isr/rtd6748/Platform  \
 drivers/rtk_kdriver/memc_isr/rtd6748/PQL  \
 drivers/rtk_kdriver/misc/rtd6748  \
 drivers/rtk_kdriver/mmc/rtd67xx  \
 drivers/rtk_kdriver/otp  \
 drivers/rtk_kdriver/pcbmgr  \
 drivers/rtk_kdriver/pcmcia  \
 drivers/rtk_kdriver/platform/tv006  \
 drivers/rtk_kdriver/pwm/rtd6748  \
 drivers/rtk_kdriver/rmm  \
 drivers/rtk_kdriver/rng  \
 drivers/rtk_kdriver/RPC64  \
 drivers/rtk_kdriver/rtice/core  \
 drivers/rtk_kdriver/rtice/services  \
 drivers/rtk_kdriver/rtkAiDrv  \
 drivers/rtk_kdriver/rtk_cec  \
 drivers/rtk_kdriver/smartcard/adapter  \
 drivers/rtk_kdriver/smartcard/core  \
 drivers/rtk_kdriver/spi_dev/rtd6748  \
 drivers/rtk_kdriver/thermal/rtd6748  \
 drivers/rtk_kdriver/tp/rtd6748  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/avd  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/hdmirx  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/hdmirx/bist  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/i3ddma  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/io  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/panel  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/pcbsource  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/scaler/ctrl  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/scalerdrv  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vbi  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vdac  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vdc  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vip  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vip/vip_ko  \
 drivers/rtk_kdriver/tvscalercontrol/rtd6748/vo  \
 drivers/rtk_kdriver/uart  \
 drivers/rtk_kdriver/usb/rtd6748  \
 drivers/rtk_kdriver/vdec/rtd6748  \
 drivers/rtk_kdriver/vgip_isr/rtd6748

export KASAN_LIST
