# Makefile for the PQ ISR.
KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/memc_isr/$(CHIP_NAME)
obj-y :=scalerVIP.o scalerDCC.o scalerVideo.o scalerDI.o scalerVideoTable.o scalerAI.o scalerHist.o scalerAiDebug.o scalerVIPDOS.o

KBUILD_CFLAGS += -Wall -Werror
