#
# Makefile for the linux kernel.
#

obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtksd_ops.o
obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc.o
obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc_raw.o
obj-$(CONFIG_MMC_RTKSD)         += rtksdio.o


