KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/CXD2856Family_refcode/Source

CXD2856Family_refcode_isdbt-objs := sony_demod_isdbt.o \
sony_demod_isdbt_monitor.o \
					
obj-y += CXD2856Family_refcode_isdbt.o 