#ifndef __SETUPDEF_PICMODE_H__
#define __SETUPDEF_PICMODE_H__

typedef enum _PICTURE_MODE {

	PICTURE_MODE_USER = 0,
	PICTURE_MODE_VIVID,
	PICTURE_MODE_STD,
	PICTURE_MODE_GENTLE,
	PICTURE_MODE_MOVIE,
	PICTURE_MODE_SPORT,
	PICTURE_MODE_GAME,
	PICTURE_MODE_AUTO_VIEW,
	PICTURE_MODE_DYNAMIC,
	PICTURE_MODE_STANDARD,
	PICTURE_MODE_MILD,
	PICTURE_MODE_ECO,
	PICTURE_MODE_PC,
	PICTURE_MODE_CRICKET,/*yuan::20130624*/
	PICTURE_MODE_MAX,

} PICTURE_MODE;

#endif