KBUILD_CPPFLAGS += -I ./
KBUILD_CPPFLAGS += -I ../include/
#KBUILD_CPPFLAGS += -I ../include/rtd2851c/rtk_kdriver/
#KBUILD_CPPFLAGS += -I ../include/rtd2851f/rtk_kdriver/

obj-$(CONFIG_RTK_MEASURE) += rtk-measure.o
rtk-measure-objs := rtk_measure.o rtk_online_measure.o
