#Copyright (C) 2007-2013 Realtek Semiconductor Corporation.
KBUILD_CFLAGS += -Wall -Werror

obj-$(CONFIG_RTK_KDRV_CEC)  += rtk-cec.o
rtk-cec-objs += core/rtk_cec_core.o \
		core/rtk_cm_buff.o  \
		core/rtk_cec_dev.o  \
		adapter/rtk_cec_priv.o \
		adapter/rtk_cec_msg.o
