# Makefile for the Realtek scaler VIP drivers.
#
#obj-y := scalerColor.o color.o dcc.o di_ma.o film.o icm.o intra.o nr.o custom_sharpness.o xc.o peaking.o ultrazoom.o gibi_od.o pq_misc_table.o pq_adaptive.o localdimming.o

#obj-y := ultrazoom.o di_ma.o scalerColor.o dcc.o color.o film.o icm.o intra.o nr.o custom_sharpness.o xc.o peaking.o gibi_od.o pq_misc_table.o pq_adaptive.o localdimming.o vip_panel_default.o viptable.o scalerColor_tv006.o scalerColor_tv043.o localcontrast.o memc_mux.o pq_3dlut_table.o pq_rpc.o still_logo_detect.o pcid.o fcic.o hdr_table.o hdr10plus.o tc_hdr.o tc_math.o tc_OEOTF_convert.o module_test_table.o

#KBUILD_CFLAGS += -Werror

obj-y := ultrazoom.o di_ma.o scalerColor.o dcc.o color.o edgesmooth.o film.o icm.o intra.o nr.o custom_sharpness.o xc.o peaking.o gibi_od.o pq_misc_table.o pq_adaptive.o localdimming.o vip_panel_default.o viptable.o scalerColor_tv006.o scalerColor_tv043.o localcontrast.o memc_mux.o pq_3dlut_table.o pq_rpc.o still_logo_detect.o pcid.o fcic.o hdr_table.o tc_hdr.o tc_math.o tc_OEOTF_convert.o module_test_table.o st2094.o

obj-$(CONFIG_RTK_AI_DRV) += ai_pq.o

KBUILD_CFLAGS += -Werror
