# Makefile for the PQ ISR.
obj-y := scalerVIP.o scalerVIPDOS.o scalerMpegnr.o scalerDCC.o scalerVideo.o scalerDI.o scalerVideoTable.o

obj-$(CONFIG_RTK_AI_DRV) += scalerAI.o

KBUILD_CFLAGS += -Wall -Werror
