# SPDX-License-Identifier: GPL-2.0
#obj-$(CONFIG_RTK_KDRV_GPIO_LED)	+= rtk_ledtrig_attr.o
#obj-$(CONFIG_RTK_LEDS_TRIGGER_TIMER)	+= rtk_ledtrig_timer.o
#obj-$(CONFIG_RTK_LEDS_TRIGGER_ONESHOT)	+= rtk_ledtrig_oneshot.o
#obj-$(CONFIG_RTK_LEDS_TRIGGER_GPIO)	+= rtk_ledtrig_gpio.o
