#
# Makefile for the linux kernel.
#
KBUILD_CFLAGS += -Werror

obj-$(CONFIG_RTK_KDRV_AMP) += rtk-amp.o
rtk-amp-objs := rtk_amp_interface.o alc1310.o ad82010.o tas5751.o tas5707.o tas5805m.o tas5711.o  alc1312.o ad82120.o ad82088.o wa6819.o WA156819.o ad82050.o
