#ifndef	__DOLBY_IDK_1_6_1_1_DOLBY_DEVICE_h__
#define	__DOLBY_IDK_1_6_1_1_DOLBY_DEVICE_h__
/* data structure for IOCTL call */

struct dolbyvision_load_vsem {
	int data_version;
	size_t data_size;
	uint8_t *data;
};

struct dolby_vision_capability_data {
	int32_t size;
	uint32_t data;
};

#define DOLBYVISIONEDR_IOC_MAGIC  'h'

#define DOLBYVISIONEDR_IOC_RB_INIT			_IOWR(DOLBYVISIONEDR_IOC_MAGIC, 0, int)
#define DOLBYVISIONEDR_IOC_RUN				_IOR(DOLBYVISIONEDR_IOC_MAGIC, 1, int)
#define DOLBYVISIONEDR_IOC_STOP				_IOR(DOLBYVISIONEDR_IOC_MAGIC, 2, int)
#define DOLBYVISIONEDR_IOC_PAUSE			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 3, int)
#define DOLBYVISIONEDR_IOC_RB_FLUSH 			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 4, int)

#define DOLBYVISIONEDR_IOC_3DLUT_UPDATE 		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 5, int)


#define DOLBYVISIONEDR_HDMI_IN_TEST 			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 6, int)
#define DOLBYVISIONEDR_NORMAL_IN_TEST			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 7, int)
#define DOLBYVISIONEDR_DM_CRF_420_TEST			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 8, int)
#define DOLBYVISIONEDR_DM_CRF_422_TEST			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 9, int)
#define DOLBYVISIONEDR_COMPOSER_CRF_TEST		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 10, int)
#define DOLBYVISIONEDR_CRF_DUMP_TEST			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 11, int)
#define DOLBYVISIONEDR_CRF_TRIGGER_TEST			_IOWR(DOLBYVISIONEDR_IOC_MAGIC, 12, int)
#define DOLBYVISIONEDR_TEST_TEST			_IOR(DOLBYVISIONEDR_IOC_MAGIC, 13, int)

#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYPICMODE 		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 14, int)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYBACKLIGHT 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 15, int)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYCONTRAST 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 16, int)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYBRIGHTNESS 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 17, int)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYCOLOR 		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 18, int)
#define DOLBYVISIONEDR_DRV_VPQ_INITDOLBYPICCONFIG	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 19, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYSWVERSION	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 20, char *)
#define DOLBYVISIONEDR_DRV_SUPPORT_STATUS		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 21, int)

#define DOLBYVISIONEDR_CRF_LOAD_VSEM			_IOW(DOLBYVISIONEDR_IOC_MAGIC, 22, struct dolbyvision_load_vsem)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYIDKVERSION	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 23, char *)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYDMVERSION	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 24, char *)

#define DOLBYVISIONEDR_DRV_VPQ_GET_CURRENT_GD_DELAY	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 25, int)
#define DOLBYVISIONEDR_DRV_VPQ_GET_GD_DELAY_TABLE	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 26, char *)
#define DOLBYVISIONEDR_DRV_VPQ_GET_CURRENT_TARGET_CONFIG _IOR(DOLBYVISIONEDR_IOC_MAGIC, 27, char *)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYPICMODE 		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 28, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYBACKLIGHT 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 29, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYCONTRAST 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 30, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBYBRIGHTNESS 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 31, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBY_CFG_PATH	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 32, char *)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBY_RUNNING_MODE 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 33, int)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBY_RESOLUTION 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 34, int *)
#define DOLBYVISIONEDR_DRV_VPQ_GETDOLBY_WAIT_CFG_PATH	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 35, char *)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBY_CFG_PATH	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 36, char *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_MODE	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 37, int)
#define DOLBYVISIONEDR_DRV_VPQ_GET_DOLBY_AMBIENT_MODE	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 38, int *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_FRONT	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 39, int64_t)
#define DOLBYVISIONEDR_DRV_VPQ_GET_DOLBY_AMBIENT_FRONT	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 40, int64_t *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_REAR	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 41, int64_t)
#define DOLBYVISIONEDR_DRV_VPQ_GET_DOLBY_AMBIENT_REAR	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 42, int64_t *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_WHITEXY	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 43, int *)
#define DOLBYVISIONEDR_DRV_VPQ_GET_DOLBY_AMBIENT_WHITEXY	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 44, int *)
#define DOLBYVISIONEDR_DRV_VPQ_CLEAR_VIEW_MODE_ID	 _IO(DOLBYVISIONEDR_IOC_MAGIC, 45)
#define DOLBYVISIONEDR_DRV_VPQ_SET_BLOCK_AMBIENT_CALL	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 46, bool)
#define DOLBYVISIONEDR_DRV_VPQ_GET_BLOCK_AMBIENT_CALL	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 47, bool *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_FRONT_FORCE	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 48, int64_t)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_MODE_FORCE	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 49, int)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_AMBIENT_FORNT_LUX	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 50, int)
#define DOLBYVISIONEDR_DRV_VPQ_GET_DOLBY_AMBIENT_FRONT_LUX	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 51, int *)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_GD_DELAY_BASE_HDMI _IOR(DOLBYVISIONEDR_IOC_MAGIC, 52, int)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_GD_DELAY_BASE_OTT  _IOR(DOLBYVISIONEDR_IOC_MAGIC, 53, int)
#define DOLBYVISIONEDR_DRV_VPQ_SET_DOLBY_GD_DELAY_BASE_HDMILL   _IOR(DOLBYVISIONEDR_IOC_MAGIC, 54, int)
#define DOLBYVISIONEDR_DRV_SET_OTT_PAUSE            _IOR(DOLBYVISIONEDR_IOC_MAGIC, 55, bool)
#define DOLBYVISIONEDR_DRV_GET_OTT_PAUSE_STATUS         _IOR(DOLBYVISIONEDR_IOC_MAGIC, 56, bool *)
#define DOLBYVISIONEDR_DRV_CHECK_VIDEO_CAP         _IOW(DOLBYVISIONEDR_IOC_MAGIC, 57, struct dolby_vision_capability_data)
#define DOLBYVISIONEDR_DRV_SET_MODEL_HASH		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 58, void *)
#define DOLBYVISIONEDR_DRV_GET_CONTENT_TYPE		_IOR(DOLBYVISIONEDR_IOC_MAGIC, 59, uint8_t *)
#define DOLBYVISIONEDR_DRV_PQ_TEXT2BIN			_IOW(DOLBYVISIONEDR_IOC_MAGIC, 63, void *)
#define DOLBYVISIONEDR_DRV_SET_GDBS_DELAY_MATRIX_TABLE  _IOW(DOLBYVISIONEDR_IOC_MAGIC, 66, struct dolby_vision_gdbs_delay_data)
#define DOLBYVISIONEDR_DRV_ENABLE_PWM			_IOW(DOLBYVISIONEDR_IOC_MAGIC, 67, bool)
#define DOLBYVISIONEDR_DRV_SET_SIGNAL_FORMAT		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 69, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_DUMP_DM_REGISTER		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 70, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_FORCE_DOLBY		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 71, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_BIT_DEPTH		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 72, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_SRC_COLOR_FORMAT		_IOW(DOLBYVISIONEDR_IOC_MAGIC, 73, uint8_t)
#define DOLBYVISIONEDR_DRV_GET_DM_DATA			_IOW(DOLBYVISIONEDR_IOC_MAGIC, 74, uint8_t)
#define DOLBYVISIONEDR_DRV_GET_DM_STRUCTURE_SIZE	_IOW(DOLBYVISIONEDR_IOC_MAGIC, 75, uint8_t)
#define DOLBYVISIONEDR_DRV_VPQ_SETDOLBYPICMODE_FORCE 	_IOR(DOLBYVISIONEDR_IOC_MAGIC, 76, int)
#define DOLBYVISIONEDR_DRV_CALL_FORCE_DOLBY_VISION_HDMI  _IO(DOLBYVISIONEDR_IOC_MAGIC, 77)
#define DOLBYVISIONEDR_DRV_CALL_FORCE_DOLBY_VISION_OTT  _IO(DOLBYVISIONEDR_IOC_MAGIC, 78)
#define DOLBYVISIONEDR_DRV_SET_CRF_AMBIENT_FLAG         _IOW(DOLBYVISIONEDR_IOC_MAGIC, 79, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_FORCE_INPUT_REGION_MODE         _IOW(DOLBYVISIONEDR_IOC_MAGIC, 80, int32_t)
#define DOLBYVISIONEDR_DRV_SET_CRF_DARK_DETAIL_FLAG     _IOW(DOLBYVISIONEDR_IOC_MAGIC, 81, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_CRF_DTV_FLAG     _IOW(DOLBYVISIONEDR_IOC_MAGIC, 82, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_CRF_BEST_PQ_FLAG     _IOW(DOLBYVISIONEDR_IOC_MAGIC, 83, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_DARK_DETAIL           _IOW(DOLBYVISIONEDR_IOC_MAGIC, 84, uint8_t)
#define DOLBYVISIONEDR_DRV_SET_CFG_BIN			 _IOW(DOLBYVISIONEDR_IOC_MAGIC, 92, uint8_t)

#define DOLBYVISIONEDR_IOC_MAXNR				 93

#define DOLBY_SW_VERSION "0.9.0"

typedef struct _DV_INIT_STRUCT_ {
	/* in-band & MD ring buffer header */
	unsigned int inband_rbh_addr;
	unsigned int md_rbh_addr;

	/* MD-parser output buffer */
	unsigned int md_output_buf_addr;
	unsigned int md_output_buf_size;
} DOLBYVISION_INIT_STRUCT;

enum dolby_vsem_type {
        DOLBY_VISION_VSEM_NONE = 0,
        DOLBY_VISION_VSEM_FORM_1,
        DOLBY_VISION_VSEM_FORM_2,
};

struct dolby_vision_pq_text_buf {
	union {
		char *buf_factory;
		uint64_t dummy_buf_factory;
	};

	union {
		size_t size_factory;
		uint64_t dummy_size_factory;
	};

	union {
		char *buf_best_pq;
		uint64_t dummy_buf_best_pq;
	};

	union {
		size_t size_best_pq;
		uint64_t dummy_size_best_pq;
	};
	union {
		char *buf_pq_bin;
		uint64_t dummy_buf_pq_bin;
	};

	union {
		size_t size_pq_bin;
		uint64_t dummy_size_pq_bin;
	};
};

struct dolby_vision_cfg_bin {
	union {
		char *data;
		uint64_t dummy_data;
	};

	int size;
};
#endif	/* __DOLBY_IDK_1_6_1_1_DOLBY_DEVICE_h__ */
