KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/CXD2856Family_refcode/Source

CXD2856Family_refcode_lib-objs := sony_math.o \
					
obj-y += CXD2856Family_refcode_lib.o 



